# Generated by Django 4.2.3 on 2023-10-06 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('celebrity_id', models.AutoField(primary_key=True, serialize=False)),
                ('celebrity_name', models.CharField(max_length=100)),
                ('celebrity_image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MovieAndCelebritiesMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celebrity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.celebrity')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movie')),
            ],
        ),
    ]
